# Generated by Django 2.0.6 on 2018-09-01 18:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='アーティスト名')),
                ('url', models.URLField(blank=True, null=True, verbose_name='ホームページ等URL')),
                ('Twitter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter ID')),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='お名前')),
                ('ticket', models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='枚数')),
            ],
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公演名')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='会場')),
                ('url', models.URLField(blank=True, null=True, verbose_name='詳細URL')),
                ('date', models.DateField(blank=True, null=True, verbose_name='公演日')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='開場')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開演')),
                ('adv', models.IntegerField(blank=True, default=0, null=True, verbose_name='予約料金')),
                ('door', models.IntegerField(blank=True, default=0, null=True, verbose_name='当日料金')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('artists', models.ManyToManyField(to='reserve.Artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='audience',
            name='live',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.Live'),
        ),
        migrations.AddField(
            model_name='audience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
