# Generated by Django 2.0.6 on 2018-08-10 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='lives',
        ),
        migrations.AddField(
            model_name='live',
            name='artists',
            field=models.ManyToManyField(to='reserve.Artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Twitter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter ID'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='アーティスト名'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='ホームページ等URL'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='name',
            field=models.CharField(max_length=30, verbose_name='お名前'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='ticket',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='枚数'),
        ),
        migrations.AlterField(
            model_name='live',
            name='adv',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='予約料金'),
        ),
        migrations.AlterField(
            model_name='live',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='公演日'),
        ),
        migrations.AlterField(
            model_name='live',
            name='door',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当日料金'),
        ),
        migrations.AlterField(
            model_name='live',
            name='name',
            field=models.CharField(max_length=200, verbose_name='公演名'),
        ),
        migrations.AlterField(
            model_name='live',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開場'),
        ),
        migrations.AlterField(
            model_name='live',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='会場'),
        ),
        migrations.AlterField(
            model_name='live',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公開日時'),
        ),
        migrations.AlterField(
            model_name='live',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開演'),
        ),
        migrations.AlterField(
            model_name='live',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='詳細URL'),
        ),
    ]
